'use client';
import React, { useState } from 'react';
import { UtensilsCrossed, Clock, Check, Sparkles, BookOpen, User, Flame, AlertCircle } from 'lucide-react';
import { Recipe } from '@/lib/types';
import { AGENT_DISPLAY_NAMES } from '@/lib/agent-display-names';

interface MealPlannerHubProps {
  recipes: Recipe[];
}

export default function MealPlannerHub({ recipes }: MealPlannerHubProps) {
  const [activeRecipeId, setActiveRecipeId] = useState<string | null>(recipes[0]?.id || null);
  const [timerRunning, setTimerRunning] = useState(false);
  const [timerCount, setTimerCount] = useState(0);
  const [timerIntervalId, setTimerIntervalId] = useState<any | null>(null);

  const activeRecipe = recipes.find((r) => r.id === activeRecipeId) || recipes[0];

  // Stop watch utility
  const toggleTimer = () => {
    if (timerRunning) {
      if (timerIntervalId) clearInterval(timerIntervalId);
      setTimerRunning(false);
    } else {
      setTimerCount(0);
      setTimerRunning(true);
      const interval = setInterval(() => {
        setTimerCount((prev) => prev + 1);
      }, 1000);
      setTimerIntervalId(interval);
    }
  };

  const formatTimer = (secs: number) => {
    const mins = Math.floor(secs / 60);
    const remaining = secs % 60;
    return `${mins.toString().padStart(2, '0')}:${remaining.toString().padStart(2, '0')}`;
  };

  return (
    <div className="space-y-8 animate-fade-in text-[#2D332D]">
      
      {/* Header section */}
      <div>
        <p className="text-[10px] uppercase tracking-[0.2em] text-[#16A34A] font-extrabold font-sans">Active Meal Hub</p>
        <h2 className="text-3xl font-serif italic font-bold text-[#14532D] mt-1">{AGENT_DISPLAY_NAMES.recipeCompiler}</h2>
        <p className="text-[#15803D] mt-2 text-sm leading-relaxed max-w-3xl">
          Observe weekly recipe schedules generated by our neural compiler. Ingredients are cross-referenced with your home cabinets while schedules designate the optimal household cook.
        </p>
      </div>

      {recipes.length === 0 ? (
        <div className="bg-white border border-[#BBF7D0] rounded-[32px] p-8 text-center text-[#15803D] shadow-sm">
          <AlertCircle className="h-10 w-10 text-[#BBF7D0] mx-auto mb-2 font-light opacity-85" />
          <p className="text-sm leading-relaxed max-w-sm mx-auto">
            No recipes compiled yet. Jump to the <strong className="text-[#14532D] font-bold font-sans">Autonomous Planner</strong>, select your parameters, and press fire!
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Left Column: Weekly Menu Selector */}
          <div className="space-y-4">
            <h3 className="font-serif font-bold text-lg text-[#14532D] border-b border-[#BBF7D0] pb-3 flex items-center gap-2">
              <UtensilsCrossed className="text-[#16A34A] h-5 w-5" /> Weekly Dinners Schedule
            </h3>

            <div className="space-y-3">
              {recipes.map((item, idx) => {
                const isActive = activeRecipeId === item.id || (!activeRecipeId && idx === 0);
                return (
                  <button
                    key={item.id}
                    onClick={() => {
                      setActiveRecipeId(item.id);
                      setTimerRunning(false);
                      setTimerCount(0);
                    }}
                    className={`w-full text-left p-4 rounded-[24px] border transition-all duration-300 cursor-pointer ${
                      isActive
                        ? 'bg-[#F0FDF4] border-[#16A34A] shadow-sm'
                        : 'bg-white border-[#BBF7D0]/60 hover:bg-[#FBFBFA]'
                    }`}
                  >
                    <div className="space-y-2">
                      <div className="flex justify-between items-start gap-4">
                        <span className="text-[10px] font-mono font-bold tracking-widest text-[#14532D] uppercase bg-[#DCFCE7] px-2.5 py-0.5 rounded-full border border-[#BBF7D0]">
                          Dinner Slot {idx + 1}
                        </span>
                        <div className="flex items-center gap-1 text-[10px] text-[#15803D] font-mono">
                          <Clock className="h-3.5 w-3.5" />
                          <span>{item.prepTimeMin + item.cookTimeMin} Mins</span>
                        </div>
                      </div>

                      <h4 className="font-bold text-[#2D332D] text-sm font-serif line-clamp-1">{item.name}</h4>

                      {/* Display some core tags */}
                      <div className="flex flex-wrap gap-1">
                        {item.dietaryTags.slice(0, 2).map((tag, tIdx) => (
                          <span key={tIdx} className="text-[9px] bg-white text-[#2D332D] px-2 py-0.5 rounded-full border border-[#BBF7D0] font-bold font-sans">
                            {tag}
                          </span>
                        ))}
                      </div>

                      <div className="pt-2 border-t border-[#BBF7D0]/65 flex items-center justify-between text-[11px] text-[#2D332D] font-bold">
                        <span className="flex items-center gap-1 text-[#14532D]">
                          <User className="h-3.5 w-3.5 text-[#16A34A]" /> Cook: <strong>{item.assignedCook}</strong>
                        </span>
                        <span className="text-[10px] font-mono bg-white px-2 py-0.5 rounded border border-[#BBF7D0]/60">
                          {item.nutritionalInfo.calories} kcal
                        </span>
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Right Column: Complete Recipe Detail & Instructions with Timer */}
          <div className="lg:col-span-2 space-y-4">
            <h3 className="font-serif font-bold text-lg text-[#14532D] border-b border-[#BBF7D0] pb-3 flex items-center justify-between">
              <span className="flex items-center gap-2">
                <BookOpen className="text-[#16A34A] h-5 w-5" /> Compilation detail
              </span>

              {/* Cooking stopwatch panel */}
              <div className="flex items-center gap-2">
                {timerRunning && (
                  <span className="font-mono text-xs font-semibold px-2.5 py-1 bg-red-100 text-red-800 border border-red-200 rounded-full animate-pulse mr-1">
                    ⏱ {formatTimer(timerCount)}
                  </span>
                )}
                <button
                  onClick={toggleTimer}
                  className="bg-[#16A34A] hover:bg-[#14532D] text-white font-extrabold uppercase tracking-wider text-[10px] px-3.5 py-2 rounded-xl cursor-pointer transition-all duration-200 shadow-sm"
                >
                  {timerRunning ? 'Stop Timer' : 'Start Cooking Timer'}
                </button>
              </div>
            </h3>

            {activeRecipe && (
              <div className="bg-white border border-[#BBF7D0] rounded-[32px] p-6 space-y-6 shadow-sm animate-fade-in">
                
                {/* Header details */}
                <div className="space-y-2">
                  <h4 className="text-xl font-bold font-serif text-[#14532D] leading-tight">{activeRecipe.name}</h4>
                  <div className="flex flex-wrap gap-1.5 pt-1">
                    {activeRecipe.dietaryTags.map((tag, idx) => (
                      <span key={idx} className="text-[10px] bg-[#DCFCE7] text-[#14532D] border border-[#BBF7D0] px-2.5 py-0.5 rounded-full font-bold font-sans">
                        {tag}
                      </span>
                    ))}
                  </div>
                  <p className="text-xs text-[#2D332D] bg-[#FBFBFA] p-4 rounded-2xl border border-[#BBF7D0]/60 italic leading-relaxed mt-2.5">
                    "Selection Logic: {activeRecipe.reasonForSelection}"
                  </p>
                </div>

                {/* Sautéing ingredients split */}
                <div className="space-y-3">
                  <span className="text-[10px] font-mono tracking-widest uppercase text-[#15803D] block pb-1 border-b border-[#BBF7D0]/60 font-bold">
                    Smart Portioning of Ingredients
                  </span>
                  
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                    {activeRecipe.ingredients.map((item, idx) => {
                      const isInventory = item.source === 'inventory';
                      return (
                        <div
                          key={idx}
                          className={`p-3 rounded-2xl border flex justify-between items-center ${
                            isInventory
                              ? 'bg-[#F0FDF4] border-[#BBF7D0] text-[#14532D]'
                              : 'bg-[#FBFBFA] border-[#BBF7D0]/50 text-[#2D332D]'
                          }`}
                        >
                          <span className="font-semibold">{item.name}</span>
                          <div className="flex items-center gap-1.5">
                            <span className="font-mono font-bold">{item.amount} {item.unit}</span>
                            <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wider font-mono ${
                              isInventory ? 'bg-[#DCFCE7] text-[#14532D] border border-[#BBF7D0]' : 'bg-stone-200 text-stone-750'
                            }`}>
                              {isInventory ? 'From Home ✓' : 'Buy Now'}
                            </span>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Preparation steps */}
                <div className="space-y-4 pt-2">
                  <span className="text-[10px] font-mono tracking-widest uppercase text-[#15803D] block pb-1 border-b border-[#BBF7D0]/60 font-bold">
                    Structured Cooking Method
                  </span>

                  <ol className="divide-y divide-[#BBF7D0]/60 text-xs">
                    {activeRecipe.instructions.map((step, idx) => (
                      <li key={idx} className="py-3 flex gap-4 items-start leading-relaxed">
                        <span className="h-6 w-6 rounded-full bg-[#DCFCE7] border border-[#BBF7D0] flex items-center justify-center font-mono font-bold text-[#14532D] flex-shrink-0">
                          {idx + 1}
                        </span>
                        <p className="text-[#2D332D] font-medium mt-0.5">{step}</p>
                      </li>
                    ))}
                  </ol>
                </div>

                {/* Nutritional info */}
                <div className="bg-[#FBFBFA] border border-[#BBF7D0] rounded-2xl p-4 text-xs space-y-2">
                  <span className="text-[9px] font-mono text-[#15803D] uppercase tracking-widest block font-bold">Dietary Health Diagnostics</span>
                  <div className="grid grid-cols-4 gap-2 text-center text-[11px] font-bold text-[#15803D]">
                    <div>
                      <p className="text-[#15803D] text-[10px] font-sans">Calories</p>
                      <p className="font-mono mt-0.5 text-[#2D332D] text-sm">{activeRecipe.nutritionalInfo.calories} kcal</p>
                    </div>
                    <div>
                      <p className="text-[#15803D] text-[10px] font-sans">Protein</p>
                      <p className="font-mono mt-0.5 text-[#2D332D] text-sm">{activeRecipe.nutritionalInfo.protein}</p>
                    </div>
                    <div>
                      <p className="text-[#15803D] text-[10px] font-sans">Sugars</p>
                      <p className="font-mono mt-0.5 text-[#16A34A] text-sm">{activeRecipe.nutritionalInfo.sugar}</p>
                    </div>
                    <div>
                      <p className="text-[#15803D] text-[10px] font-sans">Lipid Fats</p>
                      <p className="font-mono mt-0.5 text-[#2D332D] text-sm">{activeRecipe.nutritionalInfo.fat}</p>
                    </div>
                  </div>
                </div>

              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
